In [1]:
# project: p12
# submitter: mmarkovic
# partner: None
# hours: 4

In [10]:
from math import radians, cos, sin, asin, sqrt
import requests
import json
import os
import pandas as pd
from pandas import DataFrame, Series
from bs4 import BeautifulSoup

In [3]:
# Helper Functions

def download(filename, url):
    # We do not download again if the file already exists
    if os.path.exists(filename):
        return (str(filename) + " already exists!")

    r = requests.get(url)
    r.raise_for_status()
    data = r.text
    f = open(filename, "w", encoding="utf-8")
    f.write(data)
    f.close()

    return (str(filename) + " created!")

In [4]:
download("countries.json", "https://raw.githubusercontent.com/msyamkumar/cs220-s21-projects/master/p12/countries.json")

'countries.json already exists!'

In [5]:
countries = pd.read_json("countries.json")

countries.head()

,area,birth-rate,coastline,continent,country,death-rate,gdp-per-capita,infant-mortality,literacy,net-migration,phones,population,region
0,756950,15.23,0.85,South America,Chile,5.81,9900,8.80,"96,2",0.00,"213,0",16134219,LATIN AMER. & CARIB
1,665,17.80,24.21,Asia,Bahrain,4.14,16900,17.27,"89,1",1.05,"281,3",698585,NEAR EAST
2,22966,28.84,1.68,North America,Belize,5.72,4900,25.69,"94,1",0.00,"115,7",287730,LATIN AMER. & CARIB
3,582650,39.72,0.09,Africa,Kenya,14.02,1000,61.47,"85,1",-0.10,"8,1",34707817,SUB-SAHARAN AFRICA
4,11854,33.05,3.12,Australia,Marshall Islands,4.78,1600,29.45,"93,7",-6.04,"91,2",60422,OCEANIA

In [6]:
#Q1: How many countries do we have in our dataset?

len(countries)

174

In [7]:
#Q2: what is the total population across all the countries in our dataset?

countries["population"].sum()

6261901793

In [10]:
download("capitals.json", "https://raw.githubusercontent.com/msyamkumar/cs220-s21-projects/master/p12/capitals.json")

'capitals.json already exists!'

In [40]:
capitals = pd.read_json("capitals.json")

capitals.head()

       country       capital   latitude  longitude
0  Afghanistan         Kabul  34.516667  69.183333
1      Albania        Tirana  41.316667  19.816667
2      Algeria       Algiers  36.750000   3.050000
3     Anguilla    The Valley  18.216667 -63.050000
4    Argentina  Buenos Aires -34.583333 -58.666667

In [44]:
# Index capitals dataframe by row index and column index.

capitals.iloc[[4],[1]]

        capital
4  Buenos Aires

In [79]:
# Index capitals dataframe by row index column name.

capitals.loc[[2], ['longitude']]

   longitude
2       3.05

In [51]:
# Boolean indexing.

capitals[capitals['latitude']>60]

    country    capital   latitude  longitude
51  Finland   Helsinki  60.166667  24.933333
68  Iceland  Reykjavik  64.150000 -21.950000

In [60]:
# Retrieving basic information.

capitals.shape
capitals.index
capitals.columns
capitals.info()
capitals.count()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    174 non-null    object
 1   capital    174 non-null    object
 2   latitude   174 non-null    float64
 3   longitude  174 non-null    float64
dtypes: float64(2), object(2)
memory usage: 5.6+ KB

country      174
capital      174
latitude     174
longitude    174
dtype: int64

In [66]:
# Summary data.

countries['population'].sum()

countries['population'].max()
countries['population'].min()

countries['population'].mean()

35987941.33908046

In [57]:
#Q3: What are the capital names in capitals.json?

L_capitals = []

for capital in capitals["capital"]:
    L_capitals.append(capital)
    
sorted(L_capitals)

['Abu Dhabi',
 'Abuja',
 'Accra',
 'Addis Ababa',
 'Algiers',
 'Amman',
 'Amsterdam',
 'Ankara',
 'Antananarivo',
 'Apia',
 'Ashgabat',
 'Asmara',
 'Astana',
 'Asuncion',
 'Athens',
 'Baghdad',
 'Baku',
 'Bamako',
 'Bangkok',
 'Beijing',
 'Beirut',
 'Belmopan',
 'Berlin',
 'Bern',
 'Bishkek',
 'Bissau',
 'Bogota',
 'Brasilia',
 'Bridgetown',
 'Brussels',
 'Bucharest',
 'Budapest',
 'Buenos Aires',
 'Bujumbura',
 'Cairo',
 'Canberra',
 'Caracas',
 'Castries',
 'Chisinau',
 'Colombo',
 'Conakry',
 'Copenhagen',
 'Dakar',
 'Damascus',
 'Dar es Salaam',
 'Dhaka',
 'Djibouti',
 'Doha',
 'Dublin',
 'Dushanbe',
 'Freetown',
 'Gaborone',
 'George Town',
 'Georgetown',
 'Guatemala City',
 'Hagatna',
 'Hamilton',
 'Hanoi',
 'Harare',
 'Havana',
 'Helsinki',
 'Islamabad',
 'Jakarta',
 'Jamestown',
 'Jerusalem',
 'Kabul',
 'Kampala',
 'Kathmandu',
 'Khartoum',
 'Kigali',
 'Kingston',
 'Kingstown',
 'Kuala Lumpur',
 'Kuwait City',
 'Kyiv',
 'La Paz',
 'Libreville',
 'Lilongwe',
 'Lima',
 'Lisbon',
 'Ljubljana',
 'Lome',
 'London',
 'Lusaka',
 'Luxembourg',
 'Madrid',
 'Majuro',
 'Malabo',
 'Male',
 'Managua',
 'Manama',
 'Manila',
 'Maputo',
 'Maseru',
 'Mbabane',
 'Melekeok',
 'Mexico City',
 'Minsk',
 'Mogadishu',
 'Monaco',
 'Monrovia',
 'Montevideo',
 'Moroni',
 'Moscow',
 'Muscat',
 'Nairobi',
 'New Delhi',
 'Niamey',
 'Nouakchott',
 'Noumea',
 'Nuku’alofa',
 'N’Djamena',
 'Oranjestad',
 'Oslo',
 'Ottawa',
 'Ouagadougou',
 'Panama City',
 'Papeete',
 'Paramaribo',
 'Paris',
 'Phnom Penh',
 'Port Louis',
 'Port Moresby',
 'Port-Vila',
 'Port-au-Prince',
 'Porto-Novo',
 'Prague',
 'Praia',
 'Pretoria',
 'Quito',
 'Rabat',
 'Reykjavik',
 'Riga',
 'Riyadh',
 'Rome',
 'Roseau',
 'Saint George’s',
 'San Jose',
 'San Juan',
 'San Marino',
 'San Salvador',
 'Sanaa',
 'Santiago',
 'Santo Domingo',
 'Singapore',
 'Sofia',
 'Stockholm',
 'Suva',
 'Taipei',
 'Tallinn',
 'Tashkent',
 'Tbilisi',
 'Tegucigalpa',
 'Tehran',
 'The Valley',
 'Thimphu',
 'Tirana',
 'Tokyo',
 'Tripoli',
 'Tunis',
 'Ulaanbaatar',
 'Vaduz',
 'Valletta',
 'Victoria',
 'Vienna',
 'Vientiane',
 'Vilnius',
 'Warsaw',
 'Washington, D.C.',
 'Wellington',
 'Windhoek',
 'Yaounde',
 'Yerevan',
 'Zagreb']

In [33]:
#Q4: What is the capital of Sweden?

capitals[capitals['country'] == "Sweden"].iloc[0].loc["capital"]

'Stockholm'

In [14]:
#Q5: Which country's capital is Santiago?

capitals[capitals['capital'] == "Santiago"].iloc[0].loc["country"]

'Chile'

In [15]:
#Q6: Which 7 countries have the southern-most capitals?

sorted_capitals_latitude = capitals.sort_values(by = "latitude")

list(sorted_capitals_latitude["country"][0:7])

['New Zealand',
 'Australia',
 'Uruguay',
 'Argentina',
 'Chile',
 'Lesotho',
 'Swaziland']

In [16]:
#Q7: Which 10 countries have the northern-most capitals?

sorted_capitals_latitude_desc = capitals.sort_values(by = "latitude", ascending = False)

list(sorted_capitals_latitude_desc["country"][0:10])

['Iceland',
 'Finland',
 'Norway',
 'Estonia',
 'Sweden',
 'Latvia',
 'Russia',
 'Denmark',
 'Lithuania',
 'Belarus']

In [17]:
#Q8: What is the largest land-locked country in South America?

land_locked = countries[countries["coastline"] == 0]

south_america_land_locked = land_locked[land_locked["continent"] == "South America"]

south_america_land_locked_largest = south_america_land_locked[south_america_land_locked["area"] == south_america_land_locked["area"].max()]

south_america_land_locked_largest.iloc[0].loc["country"]

'Bolivia'

In [68]:
# Create a dataframe of just land-locked countries?

land_locked = countries[countries["coastline"] == 0]

land_locked

land_locked.head()

,area,birth-rate,coastline,continent,country,death-rate,gdp-per-capita,infant-mortality,literacy,net-migration,phones,population,region
12,752614,41.00,0.0,Africa,Zambia,19.93,800,88.29,"80,6",0.00,"8,2",11502010,SUB-SAHARAN AFRICA
14,447400,26.36,0.0,Asia,Uzbekistan,7.84,1700,71.10,"99,3",-1.72,"62,9",27307134,C.W. OF IND. STATES
15,61,10.02,0.0,Europe,San Marino,8.17,34600,5.73,"96,0",10.98,"704,3",29251,WESTERN EUROPE
16,488100,27.61,0.0,Asia,Turkmenistan,8.60,5800,73.08,"98,0",-0.86,"74,6",5042920,C.W. OF IND. STATES
17,33843,15.70,0.0,Europe,Moldova,12.64,1800,40.42,"99,1",-0.26,"208,1",4466706,C.W. OF IND. STATES

In [77]:
# Create a dataframe of the 7 highest net-migration countries?

countries.sort_values(by = 'net-migration', ascending = False)[0:7]

,area,birth-rate,coastline,continent,country,death-rate,gdp-per-capita,infant-mortality,literacy,net-migration,phones,population,region
65,647500,46.60,0.00,Asia,Afghanistan,20.34,700,163.07,"36,0",23.06,"3,2",31056997,ASIA (EX. NEAR EAST)
166,262,12.74,61.07,North America,Cayman Islands,4.89,35000,8.19,"98,0",18.75,"836,3",45436,LATIN AMER. & CARIB
135,11437,15.56,4.92,Asia,Qatar,4.72,21500,18.61,"82,5",16.29,"232,0",885359,NEAR EAST
97,17820,21.94,2.80,Asia,Kuwait,2.41,19000,9.95,"83,5",14.18,"211,0",2418393,NEAR EAST
28,693,9.34,27.85,Asia,Singapore,4.28,23700,2.29,"92,5",11.53,"411,4",4492150,ASIA (EX. NEAR EAST)
15,61,10.02,0.00,Europe,San Marino,8.17,34600,5.73,"96,0",10.98,"704,3",29251,WESTERN EUROPE
48,102,14.17,59.80,North America,Anguilla,5.34,8600,21.03,"95,0",10.76,"460,0",13477,LATIN AMER. & CARIB

In [18]:
#Q9: What is the largest coastal country in Africa?

coastal = countries[countries["coastline"] > 0]

africa_coastal = coastal[coastal["continent"] == "Africa"]

africa_coastal_largest = africa_coastal[africa_coastal["area"] == africa_coastal["area"].max()]

africa_coastal_largest.iloc[0].loc["country"]

'Sudan'

In [19]:
#Q10: What is coastal country with the least population in Asia?

coastal = countries[countries["coastline"] > 0]

asia_coastal = coastal[coastal["continent"] == "Asia"]

asia_coastal_smallest_pop = asia_coastal[asia_coastal["population"] == asia_coastal["population"].min()]

asia_coastal_smallest_pop.iloc[0].loc["country"]

'Maldives'

In [20]:
#Q11: What is the distance between Camp Randall Stadium and the Wisconsin State Capital?

# copied from https://stackoverflow.com/questions/4913349/haversine-formula-in-python-bearing-and-distance-between-two-gps-points
def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 3956 # Radius of earth in kilometers. Use 3956 for miles
    if c * r == 0:
        return "NaN"
    else:
        return c * r

haversine(-89.411893, 43.070231, -89.384113, 43.074645)

1.433899492072933

In [21]:
#Q12: What is the distance between Belgium and France?

Belgium = capitals[capitals["country"] == "Belgium"]
Belgium_lon = Belgium.iloc[0].loc["longitude"]
Belgium_lat = Belgium.iloc[0].loc["latitude"]

France = capitals[capitals["country"] == "France"]
France_lon = France.iloc[0].loc["longitude"]
France_lat = France.iloc[0].loc["latitude"]

haversine(Belgium_lon, Belgium_lat, France_lon, France_lat)

162.36419849726036

In [22]:
#Q13: What are the distances between Belgium, France and Spain?

def distance(country1, country2):
    country1 = capitals[capitals["country"] == country1]
    country1_lon = country1.iloc[0].loc["longitude"]
    country1_lat = country1.iloc[0].loc["latitude"]
    
    country2 = capitals[capitals["country"] == country2]
    country2_lon = country2.iloc[0].loc["longitude"]
    country2_lat = country2.iloc[0].loc["latitude"]
    
    return haversine(country1_lon, country1_lat, country2_lon, country2_lat)
    
list_countries = ["Belgium", "France", "Spain"]

list_distances = []
    
for country in list_countries:
    L = []
    L.append(distance("Belgium", country))
    L.append(distance("France", country))
    L.append(distance("Spain", country))
    list_distances.append(L)
    

DataFrame(list_distances, index = list_countries, columns = list_countries)

         Belgium   France    Spain
Belgium      NaN  162.364  816.692
France   162.364      NaN  654.572
Spain    816.692  654.572      NaN

In [23]:
#Q14: What is the distance between every pair of countries in the continent Australia?

list_countries = []

countries[countries["continent"] == "Australia"]

for country in countries[countries["continent"] == "Australia"]["country"]:
    list_countries.append(country)
    

list_distances = []

for country1 in list_countries:
    L = []
    for country2 in list_countries:
        L.append(distance(country1, country2))
    list_distances.append(L)

DataFrame(list_distances, index = list_countries, columns = list_countries)

,Marshall Islands,French Polynesia,New Zealand,Vanuatu,Palau,Papua New Guinea,Guam,Samoa,New Caledonia,Australia,Fiji,Tonga
Marshall Islands,NaN,3159.86,3348.73,1727.33,2516.3,2019.14,1861.58,1849.15,2054.91,3263.9,1806.97,2151.13
French Polynesia,3159.86,NaN,2668.81,2765.34,5447.02,4265.76,4961.13,1496.95,2864.5,3920.57,2102.14,1686.54
New Zealand,3348.73,2668.81,NaN,1671.64,4218.19,2767.61,4239.31,2062.55,1400.48,1445.15,1613.92,1510.22
Vanuatu,1727.33,2765.34,1671.64,NaN,2882.04,1527.5,2687.4,1349.9,335.603,1687.81,663.967,1098.02
Palau,2516.3,5447.02,4218.19,2882.04,NaN,1453.31,800.243,3956.31,2974.89,3099.02,3468.04,3931.84
Papua New Guinea,2019.14,4265.76,2767.61,1527.5,1453.31,NaN,1591.17,2789.12,1552.71,1786.75,2174.71,2623.74
Guam,1861.58,4961.13,4239.31,2687.4,800.243,1591.17,NaN,3520.88,2871.87,3377.1,3165.57,3617.51
Samoa,1849.15,1496.95,2062.55,1349.9,3956.31,2789.12,3520.88,NaN,1542.15,2840.09,716.316,553.393
New Caledonia,2054.91,2864.5,1400.48,335.603,2974.89,1552.71,2871.87,1542.15,NaN,1375.92,825.891,1179.07
Australia,3263.9,3920.57,1445.15,1687.81,3099.02,1786.75,3377.1,2840.09,1375.92,NaN,2145.77,2362.77
Fiji,1806.97,2102.14,1613.92,663.967,3468.04,2174.71,3165.57,716.316,825.891,2145.77,NaN,463.844
Tonga,2151.13,1686.54,1510.22,1098.02,3931.84,2623.74,3617.51,553.393,1179.07,2362.77,463.844,NaN

In [24]:
#Q15: What is the most central country in the continent Australia?

In [25]:
#Q16: What is the least central country in the continent Australia?

In [26]:
#Q17: How close is each country in the continent Australia to its nearest neighbor?

In [27]:
#Q18: How far is each country in the Australia continent to its furthest neighbor?

In [28]:
#Q19: For birth-rate and death-rate, what are various summary statistics (e.g., mean, max, standard deviation, etc.)?

countries.describe()

,area,birth-rate,coastline,death-rate,gdp-per-capita,infant-mortality,net-migration,population
count,1.740000e+02,174.000000,174.000000,174.000000,174.000000,174.000000,174.000000,1.740000e+02
mean,7.308669e+05,22.463851,10.895000,9.625172,9829.885057,37.749425,0.124425,3.598794e+07
std,2.011115e+06,11.278992,38.347494,5.187143,10624.354342,35.242398,4.479222,1.337194e+08
min,2.000000e+00,8.250000,0.000000,2.410000,500.000000,2.290000,-13.920000,7.502000e+03
25%,2.777000e+04,12.597500,0.090000,6.027500,1900.000000,8.540000,-0.907500,2.027785e+06
50%,1.375200e+05,20.010000,0.450000,8.230000,5250.000000,23.920000,0.000000,7.454650e+06
75%,5.244775e+05,29.860000,3.165000,11.715000,14725.000000,61.732500,0.815000,2.287946e+07
max,1.707520e+07,50.730000,331.660000,29.740000,55100.000000,163.070000,23.060000,1.313974e+09

In [20]:
#Q20: BeautifulSoup

download('capitals.html', 
         'https://raw.githubusercontent.com/msyamkumar/cs220-s21-projects/master/p12/techslides-snapshot.html')

# Step 2: Read the HTML file
with open('capitals.html', 'r', encoding='utf-8') as file:
    html_content = file.read()

# Step 3: Parse the HTML content with BeautifulSoup
soup = BeautifulSoup(html_content, 'html.parser')

# Step 4: (Optional) Print the parsed soup object to see the structure
# print(soup.prettify())



# Find the table in the HTML content
table = soup.find('table')

# Find all rows in the table
rows = table.find_all('tr')

# Create an empty list to hold the dictionaries
countries_data = []


valid_country_names = {country['country'] for country in countries}

valid_country_names

TypeError: string indices must be integers